### ISSUE TITLE
Unable to register on frontend

### ISSUE THREAD

**Issue by kxrt** [CS3219-AY2324S1/ay2324s1-course-assessment-g01#20]
**Description**

<img width="1171" alt="Screenshot 2023-09-17 at 10 46 54 AM" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g01/assets/73589885/4c94d766-9030-488b-93e0-a0bb2dd4734f">

I face the same error when running with both `docker-compose.yaml` and `docker-compose.dev.yaml`.

**Steps for reproducing**

- Place the environment file in the root directory
- `cd` into the root directory and run `docker-compose up --build`
- Open up `localhost:5173` (frontend URL)
- Attempt to register an account

**Expected output**

- Successful registration

**Actual output**

- Unsuccessful registration with a 500 ISE on connecting to the user service

**Other details**

Device info: MacBook Pro 2020, Intel i7

**Error Output**

On the console, I noted the following error:

```
peerprep-front-end-1         | x:xx:xx AM [vite] http proxy error at /api/v1/user/register:
peerprep-front-end-1         | Error: getaddrinfo ENOTFOUND user-service
peerprep-front-end-1         |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
```

When checking running containers with `docker container ls`, I get the following output: 

```
5f926554fcbe   mongo-express               "tini -- /docker-ent…"   4 minutes ago   Up 4 minutes   0.0.0.0:8081->8081/tcp     peerprep-mongo-express-1
79954f14b6e8   peerprep-question-service   "uvicorn app:app --h…"   4 minutes ago   Up 4 minutes   0.0.0.0:8080->8080/tcp     peerprep-question-service-1
b539cdab104a   peerprep-front-end          "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes   0.0.0.0:5173->5173/tcp     peerprep-front-end-1
374be518016c   bitnami/mongodb:latest      "/opt/bitnami/script…"   4 minutes ago   Up 4 minutes   0.0.0.0:27017->27017/tcp   peerprep-mongo-1
```

This implies the user service isn't running. However, the `peerprep-user-service` image exists as confirmed by running `docker image ls`. I then tried to have the user service run manually with `docker run --name user-service -p3000:3000 peerprep-user-service` and it seems to panic with the following error:

```
2023/09/17 xx:xx:xx /app/database/connection.go:15
[error] failed to initialize database, got error failed to connect to `host=localhost user=postgres database=dev`: dial error (dial tcp [::1]:5000: connect: cannot assign requested address)
panic: could not connect to the database

goroutine 1 [running]:
backend/database.Connect()
        /app/database/connection.go:20 +0x1d7
main.main()
        /app/main.go:16 +0x2b
exit status 2
```

I then noticed that the PostgreSQL container wasn't running either.

**Comment by kxrt** [comment]
Update: the error was that the port used by Postgres (5000) is used by Control Center/AirPlay on MacOS. Shifting this to 5001 in a later PR to prevent further conflicts.
